// <auto-generated />
using System;
using DataLayer.Func;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(ManagerContextTest))]
    [Migration("20200727092405_Init-Test")]
    partial class InitTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainLayer.Domain.Arangements.Arangement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArangementType")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndHour")
                        .HasColumnType("time");

                    b.Property<string>("LimousineName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxAmountOfHours")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartHour")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("LimousineName");

                    b.ToTable("Arangements");

                    b.HasDiscriminator<int>("ArangementType");
                });

            modelBuilder.Entity("DomainLayer.Domain.Clients.Client", b =>
                {
                    b.Property<int>("ClientNumber")
                        .HasColumnType("int");

                    b.HasKey("ClientNumber");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DomainLayer.Domain.Help.Address", b =>
                {
                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Town", "Street", "StreetNumber");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("DomainLayer.Domain.Help.ClientDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientNumber")
                        .HasColumnType("int");

                    b.Property<string>("ClientType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<int>("NrOfReservationsNeeded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientNumber");

                    b.ToTable("ClientDiscount");
                });

            modelBuilder.Entity("DomainLayer.Domain.Help.HireDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("LimousineName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LimousineName");

                    b.ToTable("HireDate");
                });

            modelBuilder.Entity("DomainLayer.Domain.Help.ReservationsPerYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientNumber")
                        .HasColumnType("int");

                    b.Property<int>("NrOfReservations")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientNumber");

                    b.ToTable("ReservationsPerYear");
                });

            modelBuilder.Entity("DomainLayer.Domain.Reservation.Details", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("DomainLayer.Domain.Reservation.Reservering", b =>
                {
                    b.Property<int>("ReservationNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientNumber")
                        .HasColumnType("int");

                    b.Property<int?>("DetailsId")
                        .HasColumnType("int");

                    b.Property<string>("LocationStreet")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationStreetNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocationTown")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationNumber");

                    b.HasIndex("ClientNumber");

                    b.HasIndex("DetailsId");

                    b.HasIndex("LocationTown", "LocationStreet", "LocationStreetNumber");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DomainLayer.Domain.Vloot.Limousine", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<int>("FirstHourPrice")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DomainLayer.Domain.Arangements.Airport", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Arangements.Arangement");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("DomainLayer.Domain.Arangements.Business", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Arangements.Arangement");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("DomainLayer.Domain.Arangements.NightLife", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Arangements.Arangement");

                    b.Property<int?>("ExtraHours")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("DomainLayer.Domain.Arangements.Wedding", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Arangements.Arangement");

                    b.Property<int?>("ExtraHours")
                        .HasColumnName("Wedding_ExtraHours")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnName("Wedding_Price")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("DomainLayer.Domain.Arangements.Wellness", b =>
                {
                    b.HasBaseType("DomainLayer.Domain.Arangements.Arangement");

                    b.Property<int>("Price")
                        .HasColumnName("Wellness_Price")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("DomainLayer.Domain.Arangements.Arangement", b =>
                {
                    b.HasOne("DomainLayer.Domain.Vloot.Limousine", null)
                        .WithMany("Arangements")
                        .HasForeignKey("LimousineName");
                });

            modelBuilder.Entity("DomainLayer.Domain.Help.ClientDiscount", b =>
                {
                    b.HasOne("DomainLayer.Domain.Clients.Client", null)
                        .WithMany("StaffelDiscount")
                        .HasForeignKey("ClientNumber");
                });

            modelBuilder.Entity("DomainLayer.Domain.Help.HireDate", b =>
                {
                    b.HasOne("DomainLayer.Domain.Vloot.Limousine", null)
                        .WithMany("HireDates")
                        .HasForeignKey("LimousineName");
                });

            modelBuilder.Entity("DomainLayer.Domain.Help.ReservationsPerYear", b =>
                {
                    b.HasOne("DomainLayer.Domain.Clients.Client", null)
                        .WithMany("PastReservations")
                        .HasForeignKey("ClientNumber");
                });

            modelBuilder.Entity("DomainLayer.Domain.Reservation.Reservering", b =>
                {
                    b.HasOne("DomainLayer.Domain.Clients.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientNumber");

                    b.HasOne("DomainLayer.Domain.Reservation.Details", "Details")
                        .WithMany()
                        .HasForeignKey("DetailsId");

                    b.HasOne("DomainLayer.Domain.Help.Address", "Location")
                        .WithMany()
                        .HasForeignKey("LocationTown", "LocationStreet", "LocationStreetNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
